In [1]:
import pandas_profiling

In [2]:
import pandas as pd
import numpy as np

In [11]:
df_machine = pd.read_csv('/home/pirl/빅데이터 프로젝트/raw data/MFG_MACHINE.csv', engine='python', encoding='EUC-KR')
df_machine

,JUDGE,LOT_ID,PANEL_ID,DATE_1BLACK,TIME_1BLACK,TIME_2AG,TIME_3BUS,TIME_4DIELEC,TIME_5MGO,TIME_6PHOS,...,MC_4DIELEC_1FIRE,MC_5MGO,MC_6PHOS_1R_1DISPENSER,MC_6PHOS_1R_2DRY,MC_6PHOS_2G_1DISPENSER,MC_6PHOS_2G_2DRY,MC_6PHOS_3B_1DISPENSER,MC_6PHOS_4FIRE,MC_7PASTE,MC_8AGING
0,양품,LOT-101,PNL-01,2019-04-01,2019-04-01 0:01,2019-04-01 5:21,2019-04-01 11:01,2019-04-06 13:41,2019-04-11 3:41,2019-04-03 20:20,...,3호기,1호기,1호기,2호기,2호기,2호기,1호기,3호기,1호기,2호기
1,양품,LOT-101,PNL-02,2019-04-01,2019-04-01 0:45,2019-04-01 6:05,2019-04-01 11:45,2019-04-06 14:25,2019-04-11 4:25,2019-04-03 21:04,...,3호기,1호기,1호기,2호기,2호기,2호기,1호기,3호기,1호기,2호기
2,양품,LOT-101,PNL-03,2019-04-01,2019-04-01 1:29,2019-04-01 6:49,2019-04-01 12:29,2019-04-06 15:09,2019-04-11 5:09,2019-04-03 21:48,...,3호기,1호기,1호기,2호기,2호기,2호기,1호기,3호기,1호기,2호기
3,양품,LOT-101,PNL-04,2019-04-01,2019-04-01 2:13,2019-04-01 7:33,2019-04-01 13:13,2019-04-06 15:53,2019-04-11 5:53,2019-04-03 22:32,...,3호기,1호기,1호기,2호기,2호기,2호기,1호기,3호기,1호기,2호기
4,양품,LOT-101,PNL-05,2019-04-01,2019-04-01 2:58,2019-04-01 8:18,2019-04-01 13:58,2019-04-06 16:38,2019-04-11 6:38,2019-04-03 23:17,...,3호기,1호기,1호기,2호기,2호기,2호기,1호기,3호기,1호기,2호기
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,명점,LOT-300,PNL-16,2019-08-01,2019-08-01 21:38,2019-08-02 2:58,2019-08-02 8:38,2019-08-07 11:18,2019-08-12 1:18,2019-08-04 14:38,...,3호기,2호기,2호기,1호기,2호기,1호기,1호기,3호기,1호기,2호기
3996,양품,LOT-300,PNL-17,2019-08-01,2019-08-01 22:23,2019-08-02 3:43,2019-08-02 9:23,2019-08-07 12:03,2019-08-12 2:03,2019-08-04 15:23,...,3호기,2호기,2호기,1호기,2호기,1호기,1호기,3호기,1호기,2호기
3997,양품,LOT-300,PNL-18,2019-08-01,2019-08-01 23:07,2019-08-02 4:27,2019-08-02 10:07,2019-08-07 12:47,2019-08-12 2:47,2019-08-04 16:07,...,3호기,2호기,2호기,1호기,2호기,1호기,1호기,3호기,1호기,2호기
3998,명점,LOT-300,PNL-19,2019-08-01,2019-08-01 23:51,2019-08-02 5:11,2019-08-02 10:51,2019-08-07 13:31,2019-08-12 3:31,2019-08-04 16:51,...,3호기,2호기,2호기,1호기,2호기,1호기,1호기,3호기,1호기,2호기
3999,양품,LOT-300,PNL-20,2019-08-02,2019-08-02 0:35,2019-08-02 5:55,2019-08-02 11:35,2019-08-07 14:15,2019-08-12 4:15,2019-08-04 17:35,...,3호기,2호기,2호기,1호기,2호기,1호기,1호기,3호기,1호기,2호기

In [10]:
df_tat = pd.read_csv('/home/pirl/빅데이터 프로젝트/raw data/MFG_TAT.csv', engine='python', encoding='EUC-KR')
df_tat

,JUDGE,LOT_ID,PANEL_ID,TIME_1BLACK,TIME_2AG,TIME_3BUS,TIME_4DIELEC,TIME_5MGO,TIME_6PHOS,TIME_7PASTE,...,TAT_4DIELEC_FIRE,TAT_5MGO,TAT_6PHOS_1R_1DISPENSER,TAT_6PHOS_1R_2DRY,TAT_6PHOS_2G_1DISPENSER,TAT_6PHOS_2G_2DRY,TAT_6PHOS_3B_1DISPENSER,TAT_6PHOS_4FIRE,TAT_7PASTE,TAT_8AGING
0,양품,LOT-101,PNL-01,2019-04-01 0:01,2019-04-01 5:21,2019-04-01 11:01,2019-04-06 13:41,2019-04-11 3:41,2019-04-03 20:20,2019-04-11 12:41,...,6447.0,530.0,76.0,333.0,88.0,396.0,86.0,7140.0,0.0,10074.0
1,양품,LOT-101,PNL-02,2019-04-01 0:45,2019-04-01 6:05,2019-04-01 11:45,2019-04-06 14:25,2019-04-11 4:25,2019-04-03 21:04,2019-04-11 13:25,...,6600.0,530.0,80.0,438.0,82.0,381.0,84.0,6956.0,0.0,10075.0
2,양품,LOT-101,PNL-03,2019-04-01 1:29,2019-04-01 6:49,2019-04-01 12:29,2019-04-06 15:09,2019-04-11 5:09,2019-04-03 21:48,2019-04-11 14:09,...,6597.0,530.0,80.0,420.0,92.0,396.0,86.0,6840.0,0.0,10645.0
3,양품,LOT-101,PNL-04,2019-04-01 2:13,2019-04-01 7:33,2019-04-01 13:13,2019-04-06 15:53,2019-04-11 5:53,2019-04-03 22:32,2019-04-11 14:53,...,6420.0,530.0,78.0,429.0,78.0,399.0,90.0,6720.0,0.0,10076.0
4,양품,LOT-101,PNL-05,2019-04-01 2:58,2019-04-01 8:18,2019-04-01 13:58,2019-04-06 16:38,2019-04-11 6:38,2019-04-03 23:17,2019-04-11 15:38,...,6453.0,540.0,76.0,363.0,82.0,393.0,84.0,7110.0,0.0,10074.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,명점,LOT-300,PNL-16,2019-08-01 21:38,2019-08-02 2:58,2019-08-02 8:38,2019-08-07 11:18,2019-08-12 1:18,2019-08-04 14:38,2019-08-12 10:18,...,6447.0,530.0,78.0,393.0,80.0,399.0,86.0,7016.0,0.0,10077.0
3996,양품,LOT-300,PNL-17,2019-08-01 22:23,2019-08-02 3:43,2019-08-02 9:23,2019-08-07 12:03,2019-08-12 2:03,2019-08-04 15:23,2019-08-12 11:03,...,NaN,530.0,80.0,405.0,78.0,402.0,78.0,6990.0,0.0,10075.0
3997,양품,LOT-300,PNL-18,2019-08-01 23:07,2019-08-02 4:27,2019-08-02 10:07,2019-08-07 12:47,2019-08-12 2:47,2019-08-04 16:07,2019-08-12 11:47,...,6447.0,540.0,78.0,375.0,100.0,360.0,84.0,7025.0,0.0,NaN
3998,명점,LOT-300,PNL-19,2019-08-01 23:51,2019-08-02 5:11,2019-08-02 10:51,2019-08-07 13:31,2019-08-12 3:31,2019-08-04 16:51,2019-08-12 12:31,...,6747.0,530.0,78.0,NaN,90.0,375.0,82.0,6960.0,0.0,9750.0
3999,양품,LOT-300,PNL-20,2019-08-02 0:35,2019-08-02 5:55,2019-08-02 11:35,2019-08-07 14:15,2019-08-12 4:15,2019-08-04 17:35,2019-08-12 13:15,...,6507.0,530.0,80.0,318.0,78.0,399.0,82.0,6865.0,0.0,10074.0

In [12]:
result_machine_tat = pd.merge(df_machine, df_tat, on=['JUDGE','LOT_ID','PANEL_ID','TIME_1BLACK','TIME_2AG','TIME_3BUS','TIME_4DIELEC','TIME_5MGO','TIME_6PHOS','TIME_7PASTE','TIME_8AGING']) # 교집합 값 inner
result_machine_tat

,JUDGE,LOT_ID,PANEL_ID,DATE_1BLACK,TIME_1BLACK,TIME_2AG,TIME_3BUS,TIME_4DIELEC,TIME_5MGO,TIME_6PHOS,...,TAT_4DIELEC_FIRE,TAT_5MGO,TAT_6PHOS_1R_1DISPENSER,TAT_6PHOS_1R_2DRY,TAT_6PHOS_2G_1DISPENSER,TAT_6PHOS_2G_2DRY,TAT_6PHOS_3B_1DISPENSER,TAT_6PHOS_4FIRE,TAT_7PASTE,TAT_8AGING
0,양품,LOT-101,PNL-01,2019-04-01,2019-04-01 0:01,2019-04-01 5:21,2019-04-01 11:01,2019-04-06 13:41,2019-04-11 3:41,2019-04-03 20:20,...,6447.0,530.0,76.0,333.0,88.0,396.0,86.0,7140.0,0.0,10074.0
1,양품,LOT-101,PNL-02,2019-04-01,2019-04-01 0:45,2019-04-01 6:05,2019-04-01 11:45,2019-04-06 14:25,2019-04-11 4:25,2019-04-03 21:04,...,6600.0,530.0,80.0,438.0,82.0,381.0,84.0,6956.0,0.0,10075.0
2,양품,LOT-101,PNL-03,2019-04-01,2019-04-01 1:29,2019-04-01 6:49,2019-04-01 12:29,2019-04-06 15:09,2019-04-11 5:09,2019-04-03 21:48,...,6597.0,530.0,80.0,420.0,92.0,396.0,86.0,6840.0,0.0,10645.0
3,양품,LOT-101,PNL-04,2019-04-01,2019-04-01 2:13,2019-04-01 7:33,2019-04-01 13:13,2019-04-06 15:53,2019-04-11 5:53,2019-04-03 22:32,...,6420.0,530.0,78.0,429.0,78.0,399.0,90.0,6720.0,0.0,10076.0
4,양품,LOT-101,PNL-05,2019-04-01,2019-04-01 2:58,2019-04-01 8:18,2019-04-01 13:58,2019-04-06 16:38,2019-04-11 6:38,2019-04-03 23:17,...,6453.0,540.0,76.0,363.0,82.0,393.0,84.0,7110.0,0.0,10074.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,명점,LOT-300,PNL-16,2019-08-01,2019-08-01 21:38,2019-08-02 2:58,2019-08-02 8:38,2019-08-07 11:18,2019-08-12 1:18,2019-08-04 14:38,...,6447.0,530.0,78.0,393.0,80.0,399.0,86.0,7016.0,0.0,10077.0
3996,양품,LOT-300,PNL-17,2019-08-01,2019-08-01 22:23,2019-08-02 3:43,2019-08-02 9:23,2019-08-07 12:03,2019-08-12 2:03,2019-08-04 15:23,...,NaN,530.0,80.0,405.0,78.0,402.0,78.0,6990.0,0.0,10075.0
3997,양품,LOT-300,PNL-18,2019-08-01,2019-08-01 23:07,2019-08-02 4:27,2019-08-02 10:07,2019-08-07 12:47,2019-08-12 2:47,2019-08-04 16:07,...,6447.0,540.0,78.0,375.0,100.0,360.0,84.0,7025.0,0.0,NaN
3998,명점,LOT-300,PNL-19,2019-08-01,2019-08-01 23:51,2019-08-02 5:11,2019-08-02 10:51,2019-08-07 13:31,2019-08-12 3:31,2019-08-04 16:51,...,6747.0,530.0,78.0,NaN,90.0,375.0,82.0,6960.0,0.0,9750.0
3999,양품,LOT-300,PNL-20,2019-08-02,2019-08-02 0:35,2019-08-02 5:55,2019-08-02 11:35,2019-08-07 14:15,2019-08-12 4:15,2019-08-04 17:35,...,6507.0,530.0,80.0,318.0,78.0,399.0,82.0,6865.0,0.0,10074.0

In [19]:
df_process = pd.read_csv('/home/pirl/빅데이터 프로젝트/raw data/MFG_PROCESS.csv', engine='python', encoding='EUC-KR')
df_process

,JUDGE,LOT_ID,PANEL_ID,TIME_1BLACK,TIME_2AG,TIME_3BUS,TIME_4DIELEC,TIME_5MGO,TIME_6PHOS,TIME_7PASTE,...,PHOS_FIRE_TEMP_KEEP_CH03,PHOS_FIRE_TEMP_KEEP_CH04,PHOS_FIRE_TEMP_ANEAL_CH01,PHOS_FIRE_TEMP_ANEAL_CH02,PHOS_FIRE_TEMP_ANEAL_CH03,PHOS_FIRE_TEMP_ANEAL_CH04,PHOS_FIRE_EXHAUST_HEAT1,PHOS_FIRE_EXHAUST_HEAT2,PHOS_FIRE_EXHAUST_HEAT3,PHOS_FIRE_EXHAUST_HEAT4
0,양품,LOT-101,PNL-01,2019-04-01T00:01,2019-04-01T05:21,2019-04-01T11:01,2019-04-06T13:41,2019-04-11T03:41,2019-04-03T20:20,2019-04-11T12:41,...,480.0,475.0,443.0,419.0,392.0,372.0,4115.0,3973.0,4432.0,2506.0
1,양품,LOT-101,PNL-02,2019-04-01T00:45,2019-04-01T06:05,2019-04-01T11:45,2019-04-06T14:25,2019-04-11T04:25,2019-04-03T21:04,2019-04-11T13:25,...,480.0,475.0,445.0,423.0,395.0,374.0,3642.0,4097.0,4499.0,2573.0
2,양품,LOT-101,PNL-03,2019-04-01T01:29,2019-04-01T06:49,2019-04-01T12:29,2019-04-06T15:09,2019-04-11T05:09,2019-04-03T21:48,2019-04-11T14:09,...,480.0,475.0,444.0,421.0,393.0,372.0,4063.0,3972.0,4460.0,2502.0
3,양품,LOT-101,PNL-04,2019-04-01T02:13,2019-04-01T07:33,2019-04-01T13:13,2019-04-06T15:53,2019-04-11T05:53,2019-04-03T22:32,2019-04-11T14:53,...,480.0,475.0,444.0,420.0,393.0,372.0,4131.0,4011.0,4466.0,2522.0
4,양품,LOT-101,PNL-05,2019-04-01T02:58,2019-04-01T08:18,2019-04-01T13:58,2019-04-06T16:38,2019-04-11T06:38,2019-04-03T23:17,2019-04-11T15:38,...,480.0,475.0,443.0,420.0,392.0,372.0,3632.0,4073.0,4482.0,2584.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,명점,LOT-300,PNL-16,2019-08-01T21:38,2019-08-02T02:58,2019-08-02T08:38,2019-08-07T11:18,2019-08-12T01:18,2019-08-04T14:38,2019-08-12T10:18,...,480.0,475.0,444.0,422.0,395.0,373.0,3615.0,4081.0,4431.0,2572.0
3996,양품,LOT-300,PNL-17,2019-08-01T22:23,2019-08-02T03:43,2019-08-02T09:23,2019-08-07T12:03,2019-08-12T02:03,2019-08-04T15:23,2019-08-12T11:03,...,480.0,475.0,443.0,421.0,392.0,371.0,3640.0,4120.0,4424.0,2566.0
3997,양품,LOT-300,PNL-18,2019-08-01T23:07,2019-08-02T04:27,2019-08-02T10:07,2019-08-07T12:47,2019-08-12T02:47,2019-08-04T16:07,2019-08-12T11:47,...,480.0,475.0,445.0,421.0,392.0,371.0,4106.0,3986.0,4425.0,2513.0
3998,명점,LOT-300,PNL-19,2019-08-01T23:51,2019-08-02T05:11,2019-08-02T10:51,2019-08-07T13:31,2019-08-12T03:31,2019-08-04T16:51,2019-08-12T12:31,...,480.0,475.0,446.0,420.0,392.0,372.0,4025.0,3942.0,4402.0,2471.0
3999,양품,LOT-300,PNL-20,2019-08-02T00:35,2019-08-02T05:55,2019-08-02T11:35,2019-08-07T14:15,2019-08-12T04:15,2019-08-04T17:35,2019-08-12T13:15,...,480.0,475.0,445.0,421.0,392.0,371.0,4079.0,4005.0,4436.0,2474.0

In [21]:
# result_all = pd.merge(result_machine_tat, df_process, on=['JUDGE','LOT_ID','PANEL_ID','TIME_1BLACK','TIME_2AG','TIME_3BUS','TIME_4DIELEC','TIME_5MGO','TIME_6PHOS','TIME_7PASTE','TIME_8AGING']) # 교집합 값 inner
result_all = pd.merge(result_machine_tat, df_process, on=['JUDGE','LOT_ID','PANEL_ID','TIME_1BLACK']) # 교집합 값 inner
result_all

Empty DataFrame
Columns: [JUDGE, LOT_ID, PANEL_ID, DATE_1BLACK, TIME_1BLACK, TIME_2AG_x, TIME_3BUS_x, TIME_4DIELEC_x, TIME_5MGO_x, TIME_6PHOS_x, TIME_7PASTE_x, TIME_8AGING_x, MC_1BLACK_1PRINT, MC_1BLACK_2RTD, MC_2AG_1PRINT, MC_2AG_2RTD, MC_2AG_3EXPOSURE, MC_3BUS_1DEVELOP, MC_3BUS_2FIRE, MC_4DIELEC_1FIRE, MC_5MGO, MC_6PHOS_1R_1DISPENSER, MC_6PHOS_1R_2DRY, MC_6PHOS_2G_1DISPENSER, MC_6PHOS_2G_2DRY, MC_6PHOS_3B_1DISPENSER, MC_6PHOS_4FIRE, MC_7PASTE, MC_8AGING, TAT_1BLACK_1PRINT, TAT_1BLACK_2RTD, TAT_2AG_1PRINT, TAT_2AG_2RTD, TAT_2AG_3EXPOSURE, TAT_3BUS_1DEVELOP, TAT_3BUS_2FIRE, TAT_4DIELEC_FIRE, TAT_5MGO, TAT_6PHOS_1R_1DISPENSER, TAT_6PHOS_1R_2DRY, TAT_6PHOS_2G_1DISPENSER, TAT_6PHOS_2G_2DRY, TAT_6PHOS_3B_1DISPENSER, TAT_6PHOS_4FIRE, TAT_7PASTE, TAT_8AGING, TIME_2AG_y, TIME_3BUS_y, TIME_4DIELEC_y, TIME_5MGO_y, TIME_6PHOS_y, TIME_7PASTE_y, TIME_8AGING_y, BLACK_RTD_TEMP_GLASS_START, BLACK_RTD_TEMP_GLASS_END, BLACK_RTD_TEMP_WALL_START, BLACK_RTD_TEMP_WALL_MAX, BLACK_RTD_PRES_START, BLACK_RTD_PRES_END, BLACK_RTD_TEMP_GLASS_OUT, BLACK_RTD_TEMP_HOOD_START, BLACK_RTD_TEMP_HOOD_MAX, AG_RTD_TEMP_GLASS_START, AG_RTD_TEMP_GLASS_END, AG_RTD_TEMP_WALL_START, AG_RTD_TEMP_WALL_MAX, AG_RTD_PRES_START, AG_RTD_PRES_END, AG_RTD_TEMP_GLASS_OUT, AG_RTD_TEMP_HOOD_START, AG_RTD_TEMP_HOOD_MAX, AG_EXPOSURE_TEMP_MASK, BUS_DEVELOP_TEMP_OVEN1, BUS_DEVELOP_TEMP_OVEN2, BUS_DEVELOP_TEMP_OVEN3, BUS_DEVELOP_PH_TANK1, BUS_DEVELOP_TEMP_TANK1, BUS_DEVELOP_PH_TANK1 2, BUS_DEVELOP_TEMP_TANK2, BUS_DEVELOP_PH_TANK1 3, BUS_DEVELOP_TEMP_TANK3, BUS_DEVELOP_PRES1, BUS_DEVELOP_PRES2, BUS_DEVELOP_PRES3, BUS_FIRE_TEMP_HEAT1_CH01, BUS_FIRE_TEMP_HEAT1_CH02, BUS_FIRE_TEMP_HEAT1_CH03, BUS_FIRE_TEMP_HEAT2_CH01, BUS_FIRE_TEMP_HEAT2_CH02, BUS_FIRE_TEMP_HEAT2_CH03, BUS_FIRE_TEMP_KEEP_CH01, BUS_FIRE_TEMP_KEEP_CH02, BUS_FIRE_TEMP_KEEP_CH03, BUS_FIRE_TEMP_ANEAL_CH01, BUS_FIRE_TEMP_ANEAL_CH02, BUS_FIRE_TEMP_ANEAL_CH03, DIELEC_FIRE_TEMP_HEAT1_CH01, DIELEC_FIRE_TEMP_HEAT1_CH02, DIELEC_FIRE_TEMP_HEAT1_CH03, DIELEC_FIRE_TEMP_HEAT2_CH01, ...]
Index: []

[0 rows x 149 columns]

In [26]:
result_all = pd.merge(result_machine_tat, df_process, on=['JUDGE','LOT_ID','PANEL_ID','TIME_1BLACK','TIME_2AG','TIME_3BUS','TIME_4DIELEC','TIME_5MGO','TIME_6PHOS','TIME_7PASTE','TIME_8AGING']) # 교집합 값 inner
# result_machine_process = pd.merge(df_machine, df_process, on=['LOT_ID']) # 교집합 값 inner
result_machine_process

,JUDGE_x,LOT_ID,PANEL_ID_x,DATE_1BLACK,TIME_1BLACK_x,TIME_2AG_x,TIME_3BUS_x,TIME_4DIELEC_x,TIME_5MGO_x,TIME_6PHOS_x,...,PHOS_FIRE_TEMP_KEEP_CH03,PHOS_FIRE_TEMP_KEEP_CH04,PHOS_FIRE_TEMP_ANEAL_CH01,PHOS_FIRE_TEMP_ANEAL_CH02,PHOS_FIRE_TEMP_ANEAL_CH03,PHOS_FIRE_TEMP_ANEAL_CH04,PHOS_FIRE_EXHAUST_HEAT1,PHOS_FIRE_EXHAUST_HEAT2,PHOS_FIRE_EXHAUST_HEAT3,PHOS_FIRE_EXHAUST_HEAT4
0,양품,LOT-101,PNL-01,2019-04-01,2019-04-01 0:01,2019-04-01 5:21,2019-04-01 11:01,2019-04-06 13:41,2019-04-11 3:41,2019-04-03 20:20,...,480.0,475.0,443.0,419.0,392.0,372.0,4115.0,3973.0,4432.0,2506.0
1,양품,LOT-101,PNL-01,2019-04-01,2019-04-01 0:01,2019-04-01 5:21,2019-04-01 11:01,2019-04-06 13:41,2019-04-11 3:41,2019-04-03 20:20,...,480.0,475.0,445.0,423.0,395.0,374.0,3642.0,4097.0,4499.0,2573.0
2,양품,LOT-101,PNL-01,2019-04-01,2019-04-01 0:01,2019-04-01 5:21,2019-04-01 11:01,2019-04-06 13:41,2019-04-11 3:41,2019-04-03 20:20,...,480.0,475.0,444.0,421.0,393.0,372.0,4063.0,3972.0,4460.0,2502.0
3,양품,LOT-101,PNL-01,2019-04-01,2019-04-01 0:01,2019-04-01 5:21,2019-04-01 11:01,2019-04-06 13:41,2019-04-11 3:41,2019-04-03 20:20,...,480.0,475.0,444.0,420.0,393.0,372.0,4131.0,4011.0,4466.0,2522.0
4,양품,LOT-101,PNL-01,2019-04-01,2019-04-01 0:01,2019-04-01 5:21,2019-04-01 11:01,2019-04-06 13:41,2019-04-11 3:41,2019-04-03 20:20,...,480.0,475.0,443.0,420.0,392.0,372.0,3632.0,4073.0,4482.0,2584.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,양품,LOT-300,PNL-20,2019-08-02,2019-08-02 0:35,2019-08-02 5:55,2019-08-02 11:35,2019-08-07 14:15,2019-08-12 4:15,2019-08-04 17:35,...,480.0,475.0,444.0,422.0,395.0,373.0,3615.0,4081.0,4431.0,2572.0
79996,양품,LOT-300,PNL-20,2019-08-02,2019-08-02 0:35,2019-08-02 5:55,2019-08-02 11:35,2019-08-07 14:15,2019-08-12 4:15,2019-08-04 17:35,...,480.0,475.0,443.0,421.0,392.0,371.0,3640.0,4120.0,4424.0,2566.0
79997,양품,LOT-300,PNL-20,2019-08-02,2019-08-02 0:35,2019-08-02 5:55,2019-08-02 11:35,2019-08-07 14:15,2019-08-12 4:15,2019-08-04 17:35,...,480.0,475.0,445.0,421.0,392.0,371.0,4106.0,3986.0,4425.0,2513.0
79998,양품,LOT-300,PNL-20,2019-08-02,2019-08-02 0:35,2019-08-02 5:55,2019-08-02 11:35,2019-08-07 14:15,2019-08-12 4:15,2019-08-04 17:35,...,480.0,475.0,446.0,420.0,392.0,372.0,4025.0,3942.0,4402.0,2471.0
79999,양품,LOT-300,PNL-20,2019-08-02,2019-08-02 0:35,2019-08-02 5:55,2019-08-02 11:35,2019-08-07 14:15,2019-08-12 4:15,2019-08-04 17:35,...,480.0,475.0,445.0,421.0,392.0,371.0,4079.0,4005.0,4436.0,2474.0

In [27]:
pr = result_machine_tat.profile_report()
pr.to_file('./pr_report_machine_tat.html')

HBox(children=(FloatProgress(value=0.0, description='variables', max=46.0, style=ProgressStyle(description_wid…

HBox(children=(FloatProgress(value=0.0, description='correlations', max=6.0, style=ProgressStyle(description_w…

HBox(children=(FloatProgress(value=0.0, description='interactions [continuous]', max=256.0, style=ProgressStyl…

HBox(children=(FloatProgress(value=0.0, description='table', max=1.0, style=ProgressStyle(description_width='i…

HBox(children=(FloatProgress(value=0.0, description='missing', max=4.0, style=ProgressStyle(description_width=…

HBox(children=(FloatProgress(value=0.0, description='warnings', max=3.0, style=ProgressStyle(description_width…

HBox(children=(FloatProgress(value=0.0, description='package', max=1.0, style=ProgressStyle(description_width=…

HBox(children=(FloatProgress(value=0.0, description='build report structure', max=1.0, style=ProgressStyle(des…